[package]
name = "uuid1"
version = "0.1.0"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[features]
serde = ["uuid/serde"]

[dependencies]
chrono = "0.4"
lazy_static = "0.2"
rand = "0.3"
uuid = { version = "0.5", features = ["v1", "v4", "use_std"] }
